channels:
  - nodefaults
  - conda-forge
  - ufs-community
dependencies:
  - flash-attn 2.8.*
  - numpy 1.26.4.*
  - python 3.12
  - setuptools 81.0.*
  - uwtools 2.14.*
  - pip:
      - anemoi-models==0.13.*
      - anemoi-training==0.10.*
