# Configuration for the NOAA RDHPCS Ursa platform.

# yamllint disable rule:anchors rule:line-length

app:
  gpu:
    batchargs: &gpu-batchargs
      --gres: 'gpu:h100:1'
      nodes: 1
      partition: u1-h100
      queue: gpuwf
  partitions:
    netaccess: u1-service
  platform: &platform
    account: epic
    scheduler: slurm
zarrs:
  common:
    execution:
      batchargs:
        --mem-per-cpu: 3G
      envcmds: !list '{{ ["source /etc/profile.d/slurm.sh"] + zarrs.common.envcmds }}'
      mpiargs:
        - "--export=ALL"
