# Configuration for the NOAA RDHPCS Ursa platform.

# yamllint disable rule:anchors rule:line-length

app:
  gpu:
    batchargs: &gpu-batchargs
      --gres: 'gpu:h100:1'
      nodes: 1
      partition: u1-h100
      queue: gpuwf
  partitions:
    netaccess: u1-service
  platform: &platform
    account: epic
    scheduler: slurm


zarrs:
  common:
    execution:
      batchargs:
        cores: 1
      mpicmd: srun --mpi=pmix
  gfs:
    zarr:
      execution:
        mpicmd: srun --mpi=pmix
  hrrr:
    zarr:
      execution:
        mpicmd: srun --mpi=pmix
